/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 50 -o sub-08/sub-08_first-L_Accu_first -m /home/sehatton/fsl/data/first/models_336_bin/L_Accu_bin.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Accu_first -o sub-08/sub-08_first-L_Accu_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 50 -o sub-08/sub-08_first-L_Amyg_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/L_Amyg.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Amyg_first -o sub-08/sub-08_first-L_Amyg_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 30 -o sub-08/sub-08_first-L_Caud_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/L_Caud.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Caud_first -o sub-08/sub-08_first-L_Caud_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 30 -o sub-08/sub-08_first-L_Hipp_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/L_Hipp.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Hipp_first -o sub-08/sub-08_first-L_Hipp_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-L_Pall_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Pall_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Pall_first -o sub-08/sub-08_first-L_Pall_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-L_Puta_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Puta_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Puta_first -o sub-08/sub-08_first-L_Puta_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-L_Thal_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/L_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-L_Thal_first -o sub-08/sub-08_first-L_Thal_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 50 -o sub-08/sub-08_first-R_Accu_first -m /home/sehatton/fsl/data/first/models_336_bin/R_Accu_bin.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Accu_first -o sub-08/sub-08_first-R_Accu_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 50 -o sub-08/sub-08_first-R_Amyg_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/R_Amyg.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Amyg_first -o sub-08/sub-08_first-R_Amyg_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 30 -o sub-08/sub-08_first-R_Caud_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/R_Caud.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Caud_first -o sub-08/sub-08_first-R_Caud_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 30 -o sub-08/sub-08_first-R_Hipp_first -m /home/sehatton/fsl/data/first/models_336_bin/intref_thal/R_Hipp.bmv -intref /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Hipp_first -o sub-08/sub-08_first-R_Hipp_corr -i sub-08/sub-08_T1w -b fast
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-R_Pall_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Pall_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Pall_first -o sub-08/sub-08_first-R_Pall_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-R_Puta_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Puta_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Puta_first -o sub-08/sub-08_first-R_Puta_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-R_Thal_first -m /home/sehatton/fsl/data/first/models_336_bin/05mm/R_Thal_05mm.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-R_Thal_first -o sub-08/sub-08_first-R_Thal_corr -i sub-08/sub-08_T1w -b none
/home/sehatton/fsl/bin/run_first -i sub-08/sub-08_T1w -t sub-08/sub-08_T1w_to_std_sub.mat -n 40 -o sub-08/sub-08_first-BrStem_first -m /home/sehatton/fsl/data/first/models_336_bin/BrStem_bin.bmv; /home/sehatton/fsl/bin/first_boundary_corr -s sub-08/sub-08_first-BrStem_first -o sub-08/sub-08_first-BrStem_corr -i sub-08/sub-08_T1w -b fast
